//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city1
    {
        public int id { get; set; }
        public string name { get; set; }
        public int id_continent { get; set; }
        public byte[] photo { get; set; }
    
        public virtual country1 country1 { get; set; }
    }
}
